### ISSUE TITLE
BabyBib pattern would not show during designer tutorial

### ISSUE THREAD

**Issue by xhokir** [joostdecock/core#240]
I started the Design tutorial part 1 up to [this part](https://freesewing.org/docs/designer/tutorial/part-1#load-the-pattern-in-your-browser) and when I try to display the pattern in browser, the page source code is empty, and the php server gives the following error:
```
[Sat Mar 10 16:10:07 2018] PHP Notice:  Undefined index: examplePart in /home/atreix/Documents/Projets/freesewing/core/patterns/Acme/BabyBib/BabyBib.php on line 133
[Sat Mar 10 16:10:07 2018] PHP Notice:  Undefined index: examplePart in /home/atreix/Documents/Projets/freesewing/core/patterns/Acme/BabyBib/BabyBib.php on line 156
[Sat Mar 10 16:10:07 2018] PHP Notice:  Undefined variable: sorted in /home/atreix/Documents/Projets/freesewing/core/patterns/Core/Pattern/Pattern.php on line 613
[Sat Mar 10 16:10:07 2018] PHP Warning:  array_shift() expects parameter 1 to be array, null given in /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php on line 53
[Sat Mar 10 16:10:07 2018] PHP Fatal error:  Uncaught Error: Call to a member function setPosition() on null in /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php:54
Stack trace:
#0 /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php(27): Freesewing\GrowingPacker->getFirstBlock(NULL)
#1 /home/atreix/Documents/Projets/freesewing/core/patterns/Core/Pattern/Pattern.php(430): Freesewing\GrowingPacker->fit(NULL)
#2 /home/atreix/Documents/Projets/freesewing/core/src/Services/DraftService.php(61): Freesewing\Patterns\Core\Pattern->layout()
#3 /home/atreix/Documents/Projets/freesewing/core/src/Context/Context.php(544): Freesewing\Services\DraftService->run(Object(Freesewing\Context))
#4 /home/atreix/Documents/Projets/freesewing/core/index.php(32): Freesewing\Context->runService()
#5 {main}
  thrown in /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php on line 54
[Sat Mar 10 16:10:07 2018] 127.0.0.1:47429 [500]: /index.php?service=draft&pattern=BabyBib&theme=Designer - Uncaught Error: Call to a member function setPosition() on null in /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php:54
Stack trace:
#0 /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php(27): Freesewing\GrowingPacker->getFirstBlock(NULL)
#1 /home/atreix/Documents/Projets/freesewing/core/patterns/Core/Pattern/Pattern.php(430): Freesewing\GrowingPacker->fit(NULL)
#2 /home/atreix/Documents/Projets/freesewing/core/src/Services/DraftService.php(61): Freesewing\Patterns\Core\Pattern->layout()
#3 /home/atreix/Documents/Projets/freesewing/core/src/Context/Context.php(544): Freesewing\Services\DraftService->run(Object(Freesewing\Context))
#4 /home/atreix/Documents/Projets/freesewing/core/index.php(32): Freesewing\Context->runService()
#5 {main}
  thrown in /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php on line 54
```
What I did:
- Installation tutorial completed successfully (the service=info&format=html works properly)
- Started the actual tutorial up to [this part](https://freesewing.org/docs/designer/tutorial/part-1#load-the-pattern-in-your-browser) and tried 3 times to follow carefully the instructions.

Config:
- Linux Mint 17
- PHP 7.2.3
- Composer 1.6.3

Thanks ! And sorry if the error is mine...

**Comment by joostdecock** [comment]
Hi there,

You have not updated the pattern config file as expected. Specifically, it complains it can't find the `examplePart` pattern part. The `examplePart` is the part used in the config file template, but in the BabyBib pattern, the part is called `bib`.

Please refer to this section: https://freesewing.org/docs/designer/tutorial/part-1#update-the-configuration-file

The template reads:

```
parts:
    examplePart: "Example Part"
```

And you should change that to:

```
parts:
    bib: "Baby bib"
```

Please let me know whether that resolved your issue. And thanks for trying freesewing :)

**Comment by xhokir** [comment]
Thanks for the quick reply ! Actually, I did update the config file. The `config.yml` is already as you mention:
```
info:
    name: "My baby bib pattern"

parts:
    bib: "Baby bib"

measurements:
    chestCircumference: 489
    headCircumference: 472

options:
    lengthBonus:
        type: "measure"
        min: -50
        max: 150
        default: 0
```
And the BabyBib.php :
```php
<?php
/** Freesewing\Patterns\Acme\BabyBib class */
namespace Freesewing\Patterns\Acme;

use Freesewing\Utils;
use Freesewing\BezierToolbox;

/**
 * Making a baby bib pattern
 */
class BabyBib extends \Freesewing\Patterns\Core\Pattern
{
    /*
        ___       _ _   _       _ _
       |_ _|_ __ (_) |_(_) __ _| (_)___  ___
        | || '_ \| | __| |/ _` | | / __|/ _ \
        | || | | | | |_| | (_| | | \__ \  __/
       |___|_| |_|_|\__|_|\__,_|_|_|___/\___|

      Things we need to do before we can draft a pattern
    */

    /**
     * Set your constants here
     */
    const EXAMPLE_CONSTANT = 52;

    /**
     * Sets up options and values for our draft
     *
     * By branching this out of the sample/draft methods, we can
     * set a bunch of options and values the influence the draft
     * without having to touch the sample/draft methods
     * When extending this pattern so we can just implement the
     * initialize() method and re-use the other methods.
     *
     * Good to know:
     * Options are typically provided by the user, but sometimes they are fixed
     * Values are calculated for re-use later
     *
     * @param \Freesewing\Model $model The model to sample for
     *
     * @return void
     */
    public function initialize($model)
    {
        // You could fix options here. For example, when you extend a
        // pattern that has options that you don't want to offer to users
        $this->setOptionIfUnset('percentOption', self::EXAMPLE_CONSTANT);

        // Set values for use later
        $this->setValue('exampleValue', time());
    }

    /*
        ____             __ _
       |  _ \ _ __ __ _ / _| |_
       | | | | '__/ _` | |_| __|
       | |_| | | | (_| |  _| |_
       |____/|_|  \__,_|_|  \__|

      The actual sampling/drafting of the pattern
    */

    /**
     * Generates a sample of the pattern
     *
     * Here, you create a sample of the pattern for a given model
     * and set of options. You should get a barebones pattern with only
     * what it takes to illustrate the effect of changes in
     * the sampled option or measurement.
     *
     * @param \Freesewing\Model $model The model to sample for
     *
     * @return void
     */
    public function sample($model)
    {
        // Setup all options and values we need
        $this->initialize($model);

        // Draft our example part
        $this->draftExamplePart($model);
    }

    /**
     * Generates a draft of the pattern
     *
     * Here, you create the full draft of this pattern for a given model
     * and set of options. You get a complete pattern with
     * all bels and whistles.
     *
     * @param \Freesewing\Model $model The model to draft for
     *
     * @return void
     */
    public function draft($model)
    {
        // Continue from sample
        $this->sample($model);

        // Finalize our example part
        $this->finalizeExamplePart($model);

        // Is this a paperless pattern?
        if ($this->isPaperless) {
            // Add paperless info to our example part
            $this->paperlessExamplePart($model);
        }
    }

    /**
     * Drafts the examplePart
     *
     * We are using a draft[part name] scheme here but
     * don't let that think that this is something specific
     * to the draft service.
     *
     * This draft method does the basic drafting and is
     * called by both the draft AND sample methods.
     *
     * The difference starts after this method is done.
     * For sample, this is all we need, but draft calls
     * the finalize[part name] method after this.
     *
     * @param \Freesewing\Model $model The model to draft for
     *
     * @return void
     */
    public function draftExamplePart($model)
    {
        /** @var \Freesewing\Part $p */
        $p = $this->parts['examplePart'];
    }

    /*
       _____ _             _ _
      |  ___(_)_ __   __ _| (_)_______
      | |_  | | '_ \ / _` | | |_  / _ \
      |  _| | | | | | (_| | | |/ /  __/
      |_|   |_|_| |_|\__,_|_|_/___\___|

      Adding titles/logos/seam-allowance/grainline and so on
    */

    /**
     * Finalizes the example part
     *
     * @param \Freesewing\Model $model The model to draft for
     *
     * @return void
     */
    public function finalizeExamplePart($model)
    {
        /** @var \Freesewing\Part $p */
        $p = $this->parts['examplePart'];
    }

    /*
        ____                       _
       |  _ \ __ _ _ __   ___ _ __| | ___  ___ ___
       | |_) / _` | '_ \ / _ \ '__| |/ _ \/ __/ __|
       |  __/ (_| | |_) |  __/ |  | |  __/\__ \__ \
       |_|   \__,_| .__/ \___|_|  |_|\___||___/___/
                  |_|

      Instructions for paperless patterns
    */

    /**
     * Adds paperless info for the example part
     *
     * @param \Freesewing\Model $model The model to draft for
     *
     * @return void
     */
    public function paperlessExamplePart($model)
    {
        /** @var \Freesewing\Part $p */
        $p = $this->parts['examplePart'];
    }
}

```

What I also tried, following your comment : remove the reference to `examplePart` (and replace by `bib`) in BabyBib.php, it just removed the first two "PHP Notice", but did not prevent the error.

**Comment by joostdecock** [comment]
Ah ok, the template code that's in your pattern file is trying to load the example part.

Comment out this line in `BabyBib.php`:

```
// Draft our example part
$this->draftExamplePart($model);
```

I'll update the template so it's commented out by default so this won't happen again.

Later in the tutorial, you'll use this line again, but adapt the draft method to use your `bib` part.

**Comment by joostdecock** [comment]
For clarify, that line is calling the `draftExamplePart` method.

In that method, there's this line:

```
$p = $this->parts['examplePart'];
```

That is the Crux of the problem, as there's no longer an `examplePart` now that you've updated the config file.

You could do a quick search and replace if you'd like, turn every `examplePart` into `bib` and you should be fine.

**Comment by xhokir** [comment]
Well, it did not solve the issue, though all "PHP Notice" related to BabyBib disappear in the log:
```
[Sat Mar 10 17:48:25 2018] PHP Notice:  Undefined variable: sorted in /home/atreix/Documents/Projets/freesewing/core/patterns/Core/Pattern/Pattern.php on line 613
[Sat Mar 10 17:48:25 2018] PHP Warning:  array_shift() expects parameter 1 to be array, null given in /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php on line 53
[Sat Mar 10 17:48:25 2018] PHP Fatal error:  Uncaught Error: Call to a member function setPosition() on null in /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php:54
Stack trace:
#0 /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php(27): Freesewing\GrowingPacker->getFirstBlock(NULL)
#1 /home/atreix/Documents/Projets/freesewing/core/patterns/Core/Pattern/Pattern.php(430): Freesewing\GrowingPacker->fit(NULL)
#2 /home/atreix/Documents/Projets/freesewing/core/src/Services/DraftService.php(61): Freesewing\Patterns\Core\Pattern->layout()
#3 /home/atreix/Documents/Projets/freesewing/core/src/Context/Context.php(544): Freesewing\Services\DraftService->run(Object(Freesewing\Context))
#4 /home/atreix/Documents/Projets/freesewing/core/index.php(32): Freesewing\Context->runService()
#5 {main}
  thrown in /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php on line 54
[Sat Mar 10 17:48:25 2018] 127.0.0.1:47711 [500]: /index.php?service=draft&pattern=BabyBib&theme=Designer - Uncaught Error: Call to a member function setPosition() on null in /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php:54
Stack trace:
#0 /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php(27): Freesewing\GrowingPacker->getFirstBlock(NULL)
#1 /home/atreix/Documents/Projets/freesewing/core/patterns/Core/Pattern/Pattern.php(430): Freesewing\GrowingPacker->fit(NULL)
#2 /home/atreix/Documents/Projets/freesewing/core/src/Services/DraftService.php(61): Freesewing\Patterns\Core\Pattern->layout()
#3 /home/atreix/Documents/Projets/freesewing/core/src/Context/Context.php(544): Freesewing\Services\DraftService->run(Object(Freesewing\Context))
#4 /home/atreix/Documents/Projets/freesewing/core/index.php(32): Freesewing\Context->runService()
#5 {main}
  thrown in /home/atreix/Documents/Projets/freesewing/core/src/GrowingPacker/GrowingPacker.php on line 54
```

**Comment by xhokir** [comment]
Slight addition: I also tried to comment the whole content of the `initialize` method, but the result is the same

**Comment by joostdecock** [comment]
Perhaps you can copy the code from here: https://github.com/freesewing/BabyBib/

At the very least that should run fine.

**Comment by xhokir** [comment]
Yes it does ! Thanks a lot. I'll go through the rest of the tutorial and let you know if I identify what was wrong.

**Comment by joostdecock** [comment]
Thank, and good luck 😀

**Comment by xhokir** [comment]
Hi again !
I continued the tutorial starting from my non-working base. It turned out that the problem disappears as soon as I completed the `draftBib` method [(here)](https://freesewing.org/docs/designer/tutorial/part-1#designing-the-neck-opening)

I tried adding the content of the method one step after the other, and actually, the problem persists until I add the last line:
```php
$p->newPath('neckOpening', 'M 1 C 3 4 2 C top3 top2 top1 C top4 top5 left1 C left3 left2 1 z');
```
And then, the pattern is properly drafted in the browser. I hope this helps ! Thanks anyway for your support !

**Comment by joostdecock** [comment]
Yes, that makes sense. I'll see if I can update the tutorial to avoid this issue. Thanks for reporting it
